### PR TITLE
New Feature: Expanding existing todos

### PR DESCRIPTION
**Pull request by NonerKao**
Please refer to #26 .

### CODE REVIEW

**Comment by NonerKao** [comment]
Sure.  Let me add some tests on this.

**Comment by gammons** [comment]
@NonerKao I like this feature.  Can you also add a PR to the gh-pages branch to update http://todolist.site as well.

**Comment by NonerKao** [comment]
Is it possible to submit a PR targeting at the gh-pages branch?  Is there any instructions or tutorial that I can follow to finish this task?
Thanks.

**Comment by gammons** [comment]
@NonerKao switch to the `gh-pages` branch, which has a totally separate source tree than `master`.  Create a new branch off of that, add your docs, then push up your branch.  You'll then be able to create a pull request that targets the `gh-pages` branch.

**Comment by NonerKao** [comment]
Thanks!

**Pull request merged**
