### PR TITLE
Golang alpine

### LINKED ISSUE #56: Building from current Dockerfile on Ubuntu 16.04 produces error.
When on Xubuntu 16.04 64-bit I run `docker build -t todolist .` I get at the end:

```
Step 8 : RUN go install github.com/gammons/todolist
 ---> Running in 8d7e755c5024
# github.com/gammons/todolist
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lpthread
/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by mikezter**
This changeset intends to fix #56

### CODE REVIEW

**Comment by gammons** [comment]
Looks good @mikezter do we need to do anything with the docker section of README.md file or are those instructions still good?

**Comment by gammons** [comment]
close #56

**Comment by mikezter** [comment]
No, I added a symlink to the container instead of changing the readme :)

**Comment by mikezter** [comment]
Sorry, i was in a hurry. I meant to say: The image still works as described in the README, no change is necessary. I decided to make the image compatible with the instructions, instead of the other way around :)

**Comment by mikezter** [comment]
@gammons What do you think about removing the MAINTAINER and last-modified lines?

i think MAINTAINER is not needed here, because let's face it, this is a really simple Dockerfile and most "maintenance" is done by the golang team :) Contributors are attributed through git. Same goes for last-modified: a comment like that is just unnecessary in the context of git.

**Comment by gammons** [comment]
@mikezter makes sense.  remove MAINTAINER and I'll merge it.

**Comment by gammons** [comment]
:tada: nice!

**Pull request merged**
