### PR TITLE
Refactor filterDay to re-use some code.

### PR DESCRIPTION
**Pull request by stuartskelton**
This is the refactor of filterDay using the newly refactored code.

This im not 100% sure about and will need some looking at, my problem is time.ParseInLocation.

Although this is used in filtering on the week, its not used within filterToExactDate.

I would be fine if you drop this one, as it may be a step too far.

### CODE REVIEW

**Comment by gammons** [comment]
@stuartskelton with https://github.com/gammons/todolist/pull/82, is this PR still relevant?

**Comment by stuartskelton** [comment]
It is relevant in the quest to reduce code, but is not necessary.  If this was merged there I would have to just add the filterOn function to the filterToExactDate.

**Comment by gammons** [comment]
@stuartskelton I intend to merge this.  Are you all good with that?

**Comment by stuartskelton** [comment]
not atm, as it will break things, I need to add the filterFunction.

**Comment by gammons** [comment]
@stuartskelton the code looks good to me and the tests pass.  Do you feel good for me to merge this one?

**Comment by stuartskelton** [comment]
yeah sure

**Comment by gammons** [comment]
thanks @stuartskelton !

**Pull request merged**
